### ISSUE TITLE
Hitta alternativ till document.execCommand

### ISSUE THREAD

**Issue by lico9292** [OSPP-breakout/Mathitor#19]
I text_mode.ts används execCommand som är en utfasad funktion som rekommenderas att man undviker. Man skulle vilja hitta ett annat sätt att få till samma funktionalitet.

**Comment by KriaPI** [comment]
I've looked at documentation and there is no alternative to the styling commands offered by document.execCommand. The only option is to add this funtionality manually. This post on StackOverflow may help: https://stackoverflow.com/questions/60581285/execcommand-is-now-obsolete-whats-the-alternative.

**Comment by KriaPI** [comment]
There is no alternative to this and it would take too much effort and time to implement it from the ground up.
